# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Robot API Tests

on:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write
  
jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
          pip install robotframework
          pip install robotframework-seleniumlibrary
          pip install robotframework-requests
          pip install robotframework-jsonlibrary
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Test with RobotFramework
      run: robot .
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        # Upload 
        path: '/home/runner/work/product-service/product-service/report.html'
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4        
